import { z } from "zod";

export const connectionSchema = z.object({
  reference: z.string().min(1),
  quotationRef: z.string().optional().or(z.literal("")),
  customerType: z.string().optional().or(z.literal("")),
  customerName: z.string().min(1),
  priority: z.string().optional().or(z.literal("")),
  customerId: z.string().optional().or(z.literal("")),
  phoneNumber: z.string().optional().or(z.literal("")),
  emailAddress: z.string().optional().or(z.literal("")),
  region: z.string().min(1),
  locality: z.string().min(1),
  constituency: z.string().min(1),
  keyStakeholder: z.string().min(1),
  plotErf: z.string().optional().or(z.literal("")),
  applicationDate: z.string().min(1),
  receivedDate: z.string().optional().or(z.literal("")),
  investigationDate: z.string().optional().or(z.literal("")),
  quoteIssuedDate: z.string().optional().or(z.literal("")),
  fullPaymentDate: z.string().optional().or(z.literal("")),
  assignedDate: z.string().optional().or(z.literal("")),
  connectionDate: z.string().optional().or(z.literal("")),
  status: z.string().min(1),
  assignedTo: z.string().optional().or(z.literal("")),
  nextAction: z.string().optional().or(z.literal("")),
  connectionClass: z.string().min(1),
  config: z.string().min(1),
  connectionType: z.string().min(1),
  projectValue: z.string().optional().or(z.literal("")),
  capitalContribution: z.string().optional().or(z.literal("")),
  mvLength: z.string().optional().or(z.literal("")),
  mvConductor: z.string().optional().or(z.literal("")),
  lvLength: z.string().optional().or(z.literal("")),
  transformerRating: z.string().optional().or(z.literal("")),
  voltageRating: z.string().optional().or(z.literal("")),
  serviceConnection: z.string().optional().or(z.literal("")),
  jobCardNumber: z.string().optional().or(z.literal("")),
  coordinates: z.string().optional().or(z.literal("")),
  coordinateSource: z.string().optional().or(z.literal("")),
  networkReference: z.string().optional().or(z.literal("")),
  mapReference: z.string().optional().or(z.literal("")),
  meterNumber: z.string().optional().or(z.literal("")),
  sealNumber: z.string().optional().or(z.literal("")),
  comment: z.string().optional().or(z.literal("")),
});

export const connectionUpdateSchema = connectionSchema.partial();
