-- Add MEMO_* notification types to NotificationType enum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEMO_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEMO_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEMO_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEMO_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEMO_REVIEWED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEMO_FORWARDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEMO_SIGNED';
